---
geometry: "left=1.5cm,right=1.5cm,top=1.5cm,bottom=1.5cm"
output:
  pdf_document:
    toc: false
header-includes:
 - \usepackage{helvet}
 - \renewcommand{\familydefault}{\sfdefault}
---

<style>
body { font-family: Helvetica, sans-serif; margin: 20px; }
.blue-panel { background-color: #e8f4f8; border: 2px solid #4a90e2; padding: 20px; margin: 20px 0; border-radius: 5px; }
h1, h2, h3 { color: #2c3e50; }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.align = "center",
  out.width = "100%",
  dev = "png",        # force PNG instead of SVG (SVG is huge for rasters)
  dpi = 300
)

library(ggplot2)
library(readr)
library(tidyr)
library(dplyr)
library(scales)
library(gridExtra)
library(grid)
library(ggtext)
library(lubridate)
library(sf)
library(patchwork)
# Additional libraries for weather data
library(httr)
library(jsonlite)

# Get coordinates of the focal station
focal_station <- stations_sf %>% filter(Station == station)

# Define bounding box (if not provided, use extent of all data)
bbox <- c(xmin = -8, xmax = -4, ymin = 49.8, ymax = 52.2)

```

```{r graphics, include=FALSE}

theme_custom <- theme_classic()+
  theme(
    axis.line = element_blank(),
    axis.text.y = element_text(angle = 90, hjust = 0.5),
    axis.text = element_text(family = "Helvetica", size = 10),
    axis.title = element_text(family = "Helvetica", size = 12),
    panel.background = element_rect(fill = "white", colour = "NA"),
    panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
    panel.grid = element_line(colour = "grey90", linewidth = 0.3),
    legend.position = "top",
    legend.title = element_blank(),
    legend.text = element_text(size = 8),
    legend.direction = "horizontal",
    plot.title = element_markdown(family = "Helvetica", color = "black", size = 16)
  )

out_folder <- "C:\\Users\\fg363\\OneDrive - University of Exeter\\Projects\\S3 Project - Documents\\Data\\SoundTrap_Summaries\\S21\\S21_9471_260213"
```

# Outputs report

## Soundscape and Noise

\vspace{0.1in}

```{r quantiles_plot, fig.width=12, fig.height=4.5, out.width="100%"}
quant_file <- file.path(paste0(out_folder,"/quantile_spectral_density_12h.csv"))

if (file.exists(quant_file)) {
  q <- read_csv(quant_file, show_col_types = FALSE)

  ggplot(q, aes(x = TOB, y = SPL, color = as.factor(percentile))) +
    geom_line(linewidth = 0.9) +
    scale_x_log10(
      breaks = c(10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000),
      labels = c("10","20","50","100","200","500","1k","2k","5k","10k","20k","50k"),
      expand = c(0,0)
    ) +
    scale_color_manual(
      values = c("1" = "#fee5d9", "5" = "#fcae91", "25" = "#fb6a4a",
                 "75" = "#de2d26", "95" = "#a50f15","99" = "darkred", "50" = "#006837"),
      labels = c("1" = "1st %ile", "5" = "5th %ile", "25" = "25th %ile", "50" = "Median",
                 "75" = "75th %ile", "95" = "95th %ile", "99" = "99th %ile")
    ) +
    theme_custom +
    theme(legend.position = "right", legend.direction = "vertical")+
    labs(title = "<b>Spectral Quantiles</b> <i style='font-size:14pt'>(Distribution of acoustic energy across TOB frequencies)</i>")+
    labs(x = "Frequency (Hz)", y = "Power (dB re 1µPa²/Hz)")
} else {
  cat("Quantiles file not found")
}

#ggsave("/Users/francescogarzon/Library/CloudStorage/OneDrive-UniversityofExeter/Projects/S3 Project - Documents/Figures/S4Station/Quatiles.jpg", last_plot(), height = 10, width = 15, units = "cm")
```


\vspace{0.2in}

```{r ltsa_plot, fig.width=12, fig.height=7, out.width="100%"}
ltsa_file <- file.path(paste0(out_folder,"/ltsa_12h.csv"))

if (file.exists(ltsa_file)) {
  ltsa <- read_csv(ltsa_file, guess_max = 10000, show_col_types = FALSE)

  ltsa$DateTime <- as.POSIXct(ltsa$DateTime, tz = "GMT")

  ggplot(ltsa, aes(x = DateTime, y = TOB, fill = SPL)) +
    geom_raster(interpolate =T) +
    geom_vline(xintercept=as.POSIXct(c("2025-11-01 00:00:00",
                                       "2025-12-01 00:00:00",
                                       "2026-01-01 00:00:00"), tz = "UTC"),
               colour = "white", linetype = 2)+
    scale_y_log10(limits = c(10,9400), expand = c(0,0),
                  breaks = c(10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 9000),
                  labels = c("10","20","50","100","200","500","1k","2k","5k","9k")) +
    scale_x_datetime(expand = c(0,0), breaks = "15 days", date_labels = "%b %d")+
    #scale_y_log10()+
    scale_fill_viridis_c(name = "Power\n(dB re 1µPa²/Hz)", na.value = "grey95", limits = c(60,115)) +
    theme_custom +
    theme(legend.position = "bottom", 
          legend.title = element_text())+
    labs(title = "<b>Long-Term Spectral Average (LTSA).</b> <i style='font-size:14pt'> Acoustic energy distribution across deployment,12-hour resolution and TOB frequency bins <br/> clipped to 10-9500 Hz.</i>")+
    labs(x = "Date", y = "Frequency (Hz)")
} else {
  cat("LTSA file not found")
}

#ggsave("/Users/francescogarzon/Library/CloudStorage/OneDrive-UniversityofExeter/Projects/S3 Project - Documents/Figures/S4Station/LTSA.jpg", last_plot(), height = 10, width = 15, units = "cm")
```

\vspace{0.1in}

```{r loud_event, fig.width=12, fig.height=6, out.width="100%"}
loud_file <- file.path(paste0(out_folder,"/loud_events.csv"))

if (file.exists(loud_file)) {
  loud <- read_csv(loud_file, show_col_types = FALSE)
  loud$DateTime <- as.POSIXct(loud$start_time)
  loud <- filter(loud,
                 #spectral_centroid_hz >=100,
                 delta_peak_dB >=10)
  
  loud_12h <- mutate(loud, DateTime12 = floor_date(DateTime, "24 hours"))%>%
    group_by(DateTime12)%>%
    summarise(ncount = n())

  count <- ggplot(data = loud_12h, aes(x = DateTime12, y = ncount))+
    geom_col(fill = "lightgrey", colour = "black", linewidth = 0.2, )+
    scale_x_datetime("Date", limits = c(start, end), expand = c(0,0), breaks = "10 days", date_labels = "%b %d")+
    scale_y_continuous("Events/day")+
    theme_custom+
    theme(axis.text.x = element_blank(),
          axis.title.x = element_blank())+
    labs(title = "<b>Broadband loud event detections.</b> <i style='font-size:14pt'> (Acoustic energy > 10dB above ambient levels) </i>")
  
  events <- ggplot(loud, aes(x = DateTime, y=spectral_centroid_hz, colour = delta_peak_dB, alpha = delta_peak_dB))+
    geom_point(size = 2, alpha = 0.8) +
    scale_y_log10("Spectral Centroid Frequency (Hz)")+
    scale_x_datetime("Date", limits = c(start, end), expand = c(0,0), breaks = "10 days", date_labels = "%b %d")+
    scale_colour_viridis_c("Delta SPL (dB)", limits = c(10,20))+
    theme_custom+
    theme(legend.position = "bottom",
          legend.title = element_text(vjust = 0.7))+
    labs(x = "Date", y = "SPL (dB re 1µPa)")
  
  grid.arrange(count, events,  ncol = 1, heights = c(0.4,1))
  
} else {
  cat("SPL file not found")
}

#ggsave("/Users/francescogarzon/Library/CloudStorage/OneDrive-UniversityofExeter/Projects/S3 Project - Documents/Figures/S4Station/TOB_SPL.jpg", last_plot(), height = 10, width = 15, units = "cm")
```

\vspace{0.1in}

```{r spl_plot, fig.width=12, fig.height=7, out.width="100%"}
spl_file <- file.path(paste0(out_folder,"/spl_timeseries_12h.csv"))

if (file.exists(spl_file)) {
  spl <- read_csv(spl_file, show_col_types = FALSE)
  spl$DateTime <- as.POSIXct(spl$DateTime)

  spl$band_hz <- ordered(spl$band_hz, levels = c(500, 200, 125, 63), labels = c("500Hz","200Hz","125Hz","63Hz"))

  ggplot(spl, aes(x = DateTime, y=mean, group = as.factor(band_hz), colour = as.factor(band_hz)))+
    geom_line(alpha = 0.8, linewidth = 0.5) +
    geom_point(size = 0.8, alpha = 0.8) +
    geom_ribbon(aes(ymin = mean-std, ymax = mean+std, fill = as.factor(band_hz)), alpha = 0.2, linewidth = 0.2)+
    facet_wrap(~as.factor(band_hz), ncol = 1)+
    scale_y_continuous("SPL (dB re 1 uPa)")+
    scale_x_datetime("Date", expand = c(0,0), breaks = "10 days", date_labels = "%b %d")+
    theme_custom+
    theme(legend.position = "none",
          strip.background =element_rect(fill="lightgrey"),
          strip.text = element_text(family = "Helvetica",size = 10))+
    labs(title = "<b>Sound Pressure Level (SPL) time series.</b> <i style='font-size:14pt'> (12-hourly averaged sound pressure levels in selected TOBs.) </i>")+
    labs(x = "Time", y = "SPL (dB re 1µPa)")
} else {
  cat("SPL file not found")
}

#ggsave("/Users/francescogarzon/Library/CloudStorage/OneDrive-UniversityofExeter/Projects/S3 Project - Documents/Figures/S4Station/TOB_SPL.jpg", last_plot(), height = 10, width = 15, units = "cm")
```

***
